services:
  - type: web
    name: sushil-portfolio
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn portfolio.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: portfolio.settings
