services:
  - type: web
    name: sushil-portfolio
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn portfolio.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: portfolio.settings
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        sync: false  # Set this in Render dashboard to include your domain
